# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: Address Elements Extraction Challenge
short_description: Shopee Code League - Address Elements Extraction
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo.jpg
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras egestas a libero nec sagittis.
evaluation_script: evaluation_script/__init__.py
remote_evaluation: False
is_docker_based: False
start_date: 2023-02-01 00:00:00
end_date: 2023-05-01 23:59:59
published: True

leaderboard:
  - id: 111
    schema:
      {
        "labels": ["Accuracy Score", "Precision", "Recall", "F1 score"],
        "default_order_by": "Accuracy Score",
        "metadata": {
          "Accuracy Score": {
            "sort_ascending": True,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          },
          "Precision": {
            "sort_ascending": True,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          },
          "Recall": {
            "sort_ascending": True,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          },
          "F1 score": {
            "sort_ascending": True,
            "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
          },
        }
      }

challenge_phases:
  - id: 222
    name: Final Phase
    description: templates/challenge_phase_1_description.html
    leaderboard_public: False
    is_public: True
    is_submission_public: True
    start_date: 2023-02-01 00:00:00
    end_date: 2023-05-01 23:59:59
    test_annotation_file: annotations/data.csv
    codename: final
    max_submissions_per_day: 10
    max_submissions_per_month: 50
    max_submissions: 50
    default_submission_meta_attributes:
      - name: method_name
        is_visible: True
      - name: method_description
        is_visible: True
      - name: project_url
        is_visible: True
      - name: publication_url
        is_visible: True
    submission_meta_attributes:
      - name: TextAttribute
        description: Sample
        type: text
        required: False
      - name: SingleOptionAttribute
        description: Sample
        type: radio
        options: ["A", "B", "C"]
      - name: MultipleChoiceAttribute
        description: Sample
        type: checkbox
        options: ["alpha", "beta", "gamma"]
      - name: TrueFalseField
        description: Sample
        type: boolean
        required: True
    is_restricted_to_select_one_submission: False
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".csv"

dataset_splits:
  - id: 333
    name: Test Split
    codename: test_split

challenge_phase_splits:
  - challenge_phase_id: 222
    leaderboard_id: 111
    dataset_split_id: 333
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
